### ISSUE TITLE
Data provider example in documentation is wrong

### ISSUE THREAD

**Issue by Kamel8330** [sebastianbergmann/phpunit-documentation-english#214] opened 2020-12-21 18:20 UTC
I believe there is an error where you return a string in a void method.
You will find it in : **Example 2.9 Combination of @depends and @dataProvider in same test**
Functions : **testProducerFirst** and **testProducerSecond**

**Comment by jrfnl** [comment] 2021-05-19 10:17
This looks to have been fixed in 2058e8cbaf08a68fde3ece9ed34f8cef92a10d3e
Issue #225 was a duplicate of this issue.

**Closed** 2021-05-19 14:36 UTC
